select
    {{ dbt_utils.generate_surrogate_key(['alert_id']) }} as alert_impact_key,
    alert_id,
    station_id,
    station_name,
    region,
    station_type,
    sector_focus,
    issued_at,
    valid_from,
    valid_to,
    alert_duration_hours,
    severity,
    alert_type,
    status,
    expected_impact_score,
    observed_incidents,
    affected_population_estimate,
    cast(incidents_per_100k_population as float) as incidents_per_100k_population,
    active_subscription_count,
    total_subscription_count,
    active_monthly_fee_units,
    active_api_calls_30d,
    cast(alert_opt_in_rate as float) as alert_opt_in_rate,
    severity_weight,
    expected_impact_score * severity_weight as weighted_impact_score
from {{ ref('int_alerts_enriched') }}
