name: 'weather_foundation'
version: '1.0.0'
config-version: 2

profile: 'weather'

dbt-cloud:
  project-id: 18521
  defer-env-id: 70568
  account_id: 664
  account-host: sa318.eu1.dbt.com

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  weather_foundation:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    mart:
      +materialized: table
      +schema: mart

seeds:
  weather_foundation:
    +schema: raw
